### ISSUE TITLE
Styling for TeaCard Component

### ISSUE THREAD

**Issue by pvinthemix** [shannonmoranetz/mentalitea#22]
Left to do:
 
**Unexpanded:**

- [x] Text on left and image on the right
- [x] border

**Expanded:**

- [x] Add images of individual teas
- [x] Add subtitle for caffeine level, category, and taste descriptors (inside a box)
- [x] Fonts
- [x] Border
- [x] Repositioning elements

**Comment by shannonmoranetz** [comment]
Optional: Image styling for unexpanded cards
-or-
Add border to image on unexpanded cards
